# -*- coding: utf-8 -*-
"""Checkpoint1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a30uzUOgIvzbV8XYIwSMOnBzDCUyCJI7
"""

#Question 1

str1 = "Jamil"
str2 ="Ben Aouicha "
print("str2 + str1 = ", str2 + str1)

#Question 2
i=7
num= (i+ ((i*10)+i) + ((i*100)+(i*10)+i))
print(num)

i=7
num= (i+ (i*11) + (i*111))
print(num)

#Question 3
num = 23
if (num % 2) == 0:
   print("{0} is Even")
else:
   print("{0} is Odd")

#Question 4
g=[]
for x in range(2000, 3200):
    if (x%7==0) and (x%5==0):
        g.append(str(x))
print (','.join(g))

#Question 5
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
n=23
print(factorial(n))